# Numpy

<h2>Introducción a NumPy – Arreglos 1D (Vectores)</h2>
<hr>

<h3>1. Arreglos 1D (Vectores)</h3>

<p>
Un arreglo 1D es una colección ordenada de elementos del mismo tipo de dato.
A diferencia de las listas de Python, los arreglos de NumPy están optimizados para cálculos matemáticos.
</p>

<ul>
  <li>Todos los elementos tienen el mismo tipo de dato.</li>
  <li>Permiten operaciones aritméticas directas.</li>
  <li>Son más eficientes que las listas para datos numéricos.</li>
</ul>

<hr>

<h3>2. Tipos de datos (dtype)</h3>

<p>
Cada arreglo de NumPy tiene un tipo de dato asociado, llamado <code>dtype</code>.
Este define el tipo de valores que almacena el arreglo.
</p>

<p>Tipos comunes:</p>
<ul>
  <li><code>int</code>: números enteros</li>
  <li><code>float</code>: números decimales</li>
  <li><code>bool</code>: valores verdadero o falso</li>
</ul>

<p>
El tipo de dato influye en la memoria utilizada y en los resultados de las operaciones matemáticas.
</p>

<hr>

<h3>3. Método <code>.round()</code></h3>

<p>
El método <code>.round()</code> se utiliza para redondear los valores de un arreglo.
</p>

<ul>
  <li>Permite indicar el número de decimales.</li>
  <li>No modifica el arreglo original si no se reasigna.</li>
  <li>Se usa principalmente para presentación de resultados.</li>
</ul>

<hr>

<h3>4. Método <code>.astype()</code></h3>

<p>
El método <code>.astype()</code> permite convertir el tipo de dato de un arreglo.
</p>

<ul>
  <li>Se utiliza para cambiar entre tipos numéricos.</li>
  <li>Genera un nuevo arreglo.</li>
  <li>Es útil para limpiar o adaptar datos.</li>
</ul>

<hr>

<h3>5. Operaciones aritméticas entre vectores</h3>

<p>
NumPy permite realizar operaciones matemáticas elemento a elemento entre arreglos.
</p>

<p>Operaciones comunes:</p>
<ul>
  <li>Suma</li>
  <li>Resta</li>
  <li>Multiplicación</li>
  <li>División</li>
</ul>

<p>
Para que estas operaciones sean válidas, los vectores deben tener la misma longitud.
</p>

<hr>

<h3>6. Operaciones con escalares</h3>

<p>
Un escalar es un único valor numérico. Al operar un vector con un escalar, la operación se aplica
a todos los elementos del arreglo.
</p>

<p>
Este comportamiento permite modificar fácilmente todos los valores de un vector sin usar bucles.
</p>

<hr>

<h3>7. Ventajas de usar NumPy</h3>

<ul>
  <li>Código más corto y legible.</li>
  <li>Mayor velocidad de ejecución.</li>
  <li>Facilidad para realizar cálculos matemáticos.</li>
</ul>

<p>
NumPy es la base para el procesamiento de datos numéricos y se integra directamente con Pandas.
</p>


<h2>Ejercicio – Procesamiento de datos con NumPy</h2>

<p>
Una tienda registra las ventas diarias (en dólares) durante una semana.
Los valores presentan decimales debido a impuestos.
</p>

<p>
Ventas registradas:
</p>

<p>
125.75, 98.40, 110.90, 87.60, 150.30, 132.95, 105.50
</p>

<p>
Se pide:
</p>

<ul>
  <li>Crear un arreglo 1D con las ventas.</li>
  <li>Mostrar el tipo de dato del arreglo.</li>
  <li>Redondear las ventas a 2 decimales.</li>
  <li>Convertir las ventas a tipo entero.</li>
  <li>Aplicar un aumento fijo de 5 dólares a todas las ventas.</li>
</ul>


In [ ]:
import numpy


# 1. Creamos el arreglo de Numpy (VECTOR === Lista pero en Numpy)

# El arreglo se crea con: numpy.array(COLECCION)

ventas = numpy.array([125.75, 98.40, 110.90, 87.60, 150.30, 132.95, 105.50])  # Creamos usando numpy.array

# Para mostrar el tipo de dato se utiliza .dtype!!!

tipo_dato = ventas.dtype # .dtype MUESTRA el tipo de datos

# 3. REDONDEAR a dos decimales - usar un ROUND()

ventas_redondeadas = ventas.round(2)  # -->> arreglo.round(Cantidad de decimales)

# 4. Convertir los datos a ENTERO

ventas_enteros = ventas_redondeadas.astype(int) # --> .astype(Tipo de datos)

# 5. SUMAR 5$ a cada venta de la lista (Del arreglo)


ventas_aumentadas = ventas_enteros + 5


# RESUMEN

"""
1. numpy.array(Coleccion_de_Datos) -> CREAR UN ARREGLO

2. arreglo.dtype() -> MOSTRAR EL TIPO DE DATO

3. arreglo.round(Cantidad_de_Decimales) -> REDONDEAR

4. arreglo.astype(Tipo_de_Dato) -> CAMBIAR el tipo de dato

5. arreglo + número -> Sumar un numero a cada valor

"""



<h2>Ejercicio 2 – Análisis básico con NumPy</h2>

<p>
Un laboratorio registra las temperaturas (en grados Celsius) medidas durante un experimento.
Los valores contienen decimales debido a la precisión del sensor.
</p>

<p>
Temperaturas registradas:
</p>

<p>
23.456, 24.891, 22.378, 25.104, 24.667, 23.982
</p>

<p>
Se pide:
</p>

<ul>
  <li>Crear un arreglo 1D con las temperaturas.</li>
  <li>Mostrar el tipo de dato del arreglo.</li>
  <li>Redondear todas las temperaturas a 1 decimal.</li>
  <li>Convertir las temperaturas a tipo entero.</li>
  <li>Calcular una corrección sumando 2 grados a todas las temperaturas enteras.</li>
  <li>Mostrar el arreglo final corregido.</li>
</ul>


In [ ]:
import numpy

temperaturas = numpy.array([23.456, 24.891, 22.378, 25.104, 24.667, 23.982])
print(temperaturas)

tipo_de_dato = temperaturas.dtype
print(tipo_de_dato)

temperaturas_redondeadas = temperaturas.round(1)
print(temperaturas_redondeadas)

temperaturas_enteros = temperaturas_redondeadas.astype(int)
print(temperaturas_enteros)

temperaturas_corregidas = temperaturas_enteros + 2
print(temperaturas_corregidas)


[23.456 24.891 22.378 25.104 24.667 23.982]
float64
[23.5 24.9 22.4 25.1 24.7 24. ]
[23 24 22 25 24 24]
[25 26 24 27 26 26]


<h2>Ejercicio 3 – Procesamiento de datos con NumPy y funciones</h2>

<p>
Un sensor registra las distancias recorridas (en metros) por un objeto en diferentes pruebas.
Los valores presentan decimales.
</p>

<p>
Distancias registradas:
</p>

<p>
12.75, 9.40, 15.60, 11.25, 14.90
</p>

<p>
Se pide implementar una función llamada <strong>procesar_distancias</strong> que reciba
una lista de distancias y realice lo siguiente:
</p>

<ul>
  <li>Crear un arreglo 1D de NumPy con las distancias.</li>
  <li>Redondear las distancias a 1 decimal.</li>
  <li>Convertir las distancias a tipo entero.</li>
  <li>Sumar 3 metros a todas las distancias enteras.</li>
  <li>Retornar el arreglo final procesado.</li>
</ul>

<p>
Finalmente, llamar a la función y mostrar el resultado.
</p>


In [ ]:
import numpy as np

def procesar_distancias(lista_distancias):
    """
    Función que procesa una lista de distancias usando NumPy.
    """
    # Convertir la lista en un arreglo de NumPy
    distancias = np.array(lista_distancias)

    # Redondear a 1 decimal
    dist_red = distancias.round(1)

    # Convertir a enteros
    dist_int = dist_red.astype(int)

    # Sumar 3 metros a todas las distancias
    dist_final = dist_int + 3

    # Retornar el arreglo procesado
    return dist_final


# Lista de distancias
datos = [12.75, 9.40, 15.60, 11.25, 14.90]

# Llamada a la función
resultado = procesar_distancias(datos)

# Mostrar resultado
print(resultado)


# Pandas

<h2>Introducción a Pandas</h2>

<p>
Pandas es una biblioteca de Python utilizada para el <strong>procesamiento y análisis de datos</strong>.
Permite trabajar con datos estructurados de forma similar a una hoja de cálculo o una tabla de base de datos.
</p>

<hr>

<h3>1. Estructuras principales de Pandas</h3>

<p>
Pandas trabaja principalmente con dos estructuras de datos:
</p>

<ul>
  <li><strong>Series</strong></li>
  <li><strong>DataFrame</strong></li>
</ul>

<hr>

<h3>2. Series</h3>

<p>
Una <strong>Series</strong> es una estructura unidimensional que almacena una secuencia de valores
asociados a un índice.
</p>

<ul>
  <li>Es similar a un vector o lista.</li>
  <li>Cada valor tiene una etiqueta (índice).</li>
  <li>Puede almacenar números, texto u otros tipos de datos.</li>
</ul>

<p>
Las Series se pueden crear a partir de:
</p>

<ul>
  <li>Listas</li>
  <li>Diccionarios</li>
  <li>Arreglos 1D de NumPy</li>
</ul>

<hr>

<h3>3. DataFrame</h3>

<p>
Un <strong>DataFrame</strong> es una estructura bidimensional formada por filas y columnas.
Cada columna es una Series.
</p>

<ul>
  <li>Permite trabajar con datos tabulares.</li>
  <li>Las columnas pueden tener distintos tipos de datos.</li>
  <li>Es la estructura más utilizada en Pandas.</li>
</ul>

<p>
Un DataFrame se puede crear desde:
</p>

<ul>
  <li>Diccionarios</li>
  <li>Listas de listas</li>
  <li>Arreglos de NumPy</li>
</ul>

<hr>

<h3>4. Índices en Pandas</h3>

<p>
El índice identifica las filas de una Series o un DataFrame.
</p>

<ul>
  <li><strong>Índice numérico</strong>: es el índice por defecto.</li>
  <li><strong>Índice no numérico</strong>: puede ser texto, códigos o etiquetas.</li>
</ul>

<p>
El uso de índices facilita la selección y organización de los datos.
</p>

<hr>

<h3>5. Selección de datos</h3>

<p>
Pandas permite acceder a la información de distintas formas:
</p>

<ul>
  <li>Selección de columnas por nombre.</li>
  <li>Selección de filas por índice.</li>
</ul>

<p>
Para seleccionar filas se utilizan principalmente:
</p>

<ul>
  <li><code>.loc</code>: selección por etiquetas.</li>
  <li><code>.iloc</code>: selección por posición numérica.</li>
</ul>

<hr>

<h3>6. Agregar columnas a un DataFrame</h3>

<p>
Es posible agregar nuevas columnas a un DataFrame de forma directa.
</p>

<ul>
  <li>Las columnas pueden tener valores fijos.</li>
  <li>Pueden derivarse de cálculos con otras columnas.</li>
</ul>

<p>
Esto permite transformar y enriquecer los datos fácilmente.
</p>

<hr>

<h3>7. Métodos básicos de análisis</h3>

<p>
Pandas incluye métodos para inspeccionar y analizar los datos:
</p>

<ul>
  <li><code>.info()</code>: muestra información general del DataFrame.</li>
  <li><code>.describe()</code>: genera estadísticas descriptivas.</li>
  <li><code>.mean()</code>: calcula el promedio.</li>
  <li><code>.sum()</code>: calcula la suma.</li>
  <li><code>.min()</code> y <code>.max()</code>: valores mínimo y máximo.</li>
</ul>

<hr>

<h3>8. Métodos de visualización rápida</h3>

<ul>
  <li><code>.head()</code>: muestra las primeras filas.</li>
  <li><code>.tail()</code>: muestra las últimas filas.</li>
</ul>

<p>
Estos métodos se utilizan para verificar rápidamente la estructura y el contenido de los datos.
</p>

<hr>

<h3>9. Importancia de Pandas</h3>

<p>
Pandas es fundamental para:
</p>

<ul>
  <li>Organizar datos.</li>
  <li>Realizar análisis estadístico básico.</li>
  <li>Preparar datos para visualización o modelos.</li>
</ul>

<p>
Se integra directamente con NumPy y otras bibliotecas de análisis de datos.
</p>


<h2>Ejercicio 1 – Introducción a Pandas</h2>

<p>
Una tienda registra el precio de algunos productos básicos.
Se cuenta con la siguiente información:
</p>

<ul>
  <li>Productos: Arroz, Leche, Pan, Huevos, Queso</li>
  <li>Precios (en dólares): 1.25, 0.90, 0.35, 2.10, 3.50</li>
</ul>

<p>
Se pide:
</p>

<ul>
  <li>Crear un DataFrame con dos columnas llamadas <strong>Producto</strong> y <strong>Precio</strong>.</li>
  <li>Mostrar las primeras filas del DataFrame.</li>
  <li>Mostrar la información general del DataFrame.</li>
  <li>Calcular el precio promedio de los productos.</li>
  <li>Mostrar el precio mínimo y el precio máximo.</li>
</ul>


In [ ]:
import pandas

# Productos: Arroz, Leche, Pan, Huevos, Queso
# Precios (en dólares): 1.25, 0.90, 0.35, 2.10, 3.50

productos = ["Arroz", "Leche", "Pan", "Huevos", "Queso"]
precios =   [1.25, 0.90, 0.35, 2.10, 3.50]


# CREAR un dataframe

# dataframe = pandas.DataFrame()  # IMPORTANTE, D mayuscula y F mayuscula

dic_productos = {
    "Producto": productos,
    "Precio" : precios
}

df = pandas.DataFrame(dic_productos)

print(df)
# MOSTRAR SOLO la primera fila


# Mostrar la informacion general del DF
# df.info()


# CALCULAR EL PROMEDIO DE LOS PRODUCTOS!!!
# OBTENER solo los PRECIOS y promediarlos

promedio = df["Precio"].mean() # Obtiene el promedio!!

print(f"El promedio de precios es: {promedio}")


minimo = df["Precio"].min()
maximo = df["Precio"].max()

print(f"El maximo es: {maximo}, y el minimo es: {minimo}")



  Producto  Precio
0    Arroz    1.25
1    Leche    0.90
2      Pan    0.35
3   Huevos    2.10
4    Queso    3.50
El promedio de precios es: 1.6199999999999999
El maximo es: 3.5, y el minimo es: 0.35


<h2>Ejercicio 2 – Índices y selección en Pandas</h2>

<p>
Una biblioteca registra la cantidad de libros disponibles por categoría.
Se cuenta con la siguiente información:
</p>

<ul>
  <li>Categorías: Ciencia, Historia, Literatura, Matemáticas, Arte</li>
  <li>Cantidad de libros: 120, 85, 200, 150, 60</li>
</ul>

<p>
Se pide:
</p>

<ul>
  <li>Crear un DataFrame con dos columnas: <strong>Categoria</strong> y <strong>Cantidad</strong>.</li>
  <li>Establecer la columna <strong>Categoria</strong> como índice del DataFrame.</li>
  <li>Mostrar el DataFrame completo.</li>
  <li>Usar <code>.loc</code> para mostrar la información de la categoría <strong>Literatura</strong>.</li>
  <li>Usar <code>.iloc</code> para mostrar la tercera fila del DataFrame.</li>
  <li>Calcular la cantidad total de libros.</li>
</ul>


In [ ]:
import pandas

# 1. Crear un DATAFRAME -- Necesitamos una COLECCION DE DATOS!!!

dic_libreria = {
    "Categoria" : ["Ciencia", "Historia", "Literatura", "Matemáticas", "Arte"],
    "Cantidad"  : [120, 85, 200, 150, 60]
}

df = pandas.DataFrame(dic_libreria) # Creamos esta vaina!!

# 2. Establecer las categorias como INDICES!!

df = df.set_index("Categoria")  # Dataframe.set_index("ETIQUETA")

# 3. Mostrar el Data Frame
print(df)

# 4. Mostrar la fila de LITERATURA --> Indice NO numerico --> .loc

fila_literatura = df.loc["Literatura"]
print(f"\n{fila_literatura}")

# 5 Mostrar TERCERA fila --> Indice NUMERICO --> .iloc

fila_tercera = df.iloc[2]  # Se cuenta desde el 0 !!

print(f"\n{fila_tercera}")

# 6 SUMAR la cantidad total de Libros

total_libros = df["Cantidad"].sum()

print(f"\nLa cantidad total de libros es: {total_libros}")




             Cantidad
Categoria            
Ciencia           120
Historia           85
Literatura        200
Matemáticas       150
Arte               60

Cantidad    200
Name: Literatura, dtype: int64

Cantidad    200
Name: Literatura, dtype: int64

La cantidad total de libros es: 615


# ASISTENCIA EN EL CHAT --> Paralelo Nombre y Matricula!!